repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-yaml
    - id: check-shebang-scripts-are-executable
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: trailing-whitespace
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 3.0.0
  hooks:
    - id: script-must-have-extension
    - id: shfmt
    - id: shellcheck
    # don't use jumanjihouse's markdownlint hoot -it requires ruby
- repo: https://github.com/jackdewinter/pymarkdown
  rev: v0.9.8
  hooks:
    - id: pymarkdown
